resources:
  - url: http://127.0.0.1:5000/rain-meter-card.js
    type: module
views:
  - cards:
      - type: custom:rain-meter-card
        name: Rain Gauge Card Development
        entity: sun.sun
        test_gui: true
